name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
      
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Cache dependencies to speed up installs
      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 4: Clean npm cache (to avoid issues with old dependencies)
      - run: npm cache clean --force

      # Step 5: Install dependencies
      - run: npm ci

      # Step 6: Run build script (if available)
      - name: Build the project
        run: npm run build --if-present

      # Step 7: Run tests
      - name: Run tests
        run: npm test

      # Step 8: Upload build artifacts (optional)
      # If you want to store build artifacts like logs or build files
      # - name: Upload build artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: build
      #     path: ./build

      # Optional: Step 9 - Notify on failure or success (e.g., Slack integration)
      # You can also integrate notification tools like Slack to alert on build failure/success
